server:
  home_dir: "~/.cyberfabric"
logging:
  default:
    console_level: info
opentelemetry:
  resource:
    service_name: "cyberfabric"
    attributes:
      project_name: "hello_world"
  exporter:
    kind: otlp_grpc
  tracing:
    enabled: false
  metrics:
    enabled: false
modules:
  hello-world:
    config:
      interval: 1
    metadata:
      package: "hello-world"
      version: "0.0.1"
